### PR TITLE
Set up integration tests for the data in all charts

### LINKED ISSUE #44: Test each new sensordata display component
Test each component so takes it's defined data and display it correctly 
- [ ] Light sensor in front of the device
- [ ] Sound level surrounding the device
- [ ] Accelerometer

Relates issue: #38 

Definition of done: When each component test and it fullfils: is able recive data and is able to display data

### PR DESCRIPTION
**Pull request by OliviaWork**
Except for TemperatureChart, as it still uses dummy data, meaning the tests cannot be done. The tests rely on the current amplify mocking system, as amplify is incredibly difficult to test without using proper mocking (like what's possible in component- and unit tests).

The tests consist of a few steps: the first validates that the mocking system is in place (as it requires manual, server-sided configuration, because Cypress). After that, it validates the existence of the charts. Finally, it inputs data, and validates that the rendered data is the expected data by using the labels. Recharts does not store raw data directly in the HTML for some reason, which means labels is the easiest way to test that the charts display the expected data.

For now, the data provided is consistent dummy data, and that's generated to ensure no point has a unique value (though the timestamps are fixed, the values are not). This is done to ensure the overall graph rendering doesn't rely on some shared state that makes several graphs render the same content when that's undesirable. 

Closes #44, though this framework does not extend to the upcoming geolocation component. Testing that will likely require more creative mocking, or maybe using component tests and proper mocking.

### CODE REVIEW

**Review by javidaf — COMMENTED** [review]
Well done, good workaround from amplify moching, however certain configurations will be changed in using amplify with authetication and autheticated user signin. The merge should wait until then

**Comment by OliviaWork** [comment]
Why exactly? 

The amplify mocking has already been merged into main (#67, hotfix in #92). The only change made here is documenting that change in the README. The only code thing related to the mocking is using Amplify's disabled status to enable the hidden input fields

**Comment by OliviaWork** [comment]
Also means that as long as whatever the change you had in mind is, as long as `amplifyInstance == null` when mocking (which is guaranteed via the environment variable that is already on main), the tests will work

**Comment by javidaf** [comment]
Yes I see, we should have actually waited testing amplify since the first apporach was as discussed not secure and only an inital approach to make the full path connection work between flutter and web through cloud.  

THe future changes:

1. we wont use env variables exactly in the same way. 
2.  AmplifyInstance will be contrsucted but data are not reciveable until user is signed in.

I am thinking that this will pose extra work until signin is properly setup.

**Comment by OliviaWork** [comment]
There's no testing amplify here though. The point is explicitly disabling Amplify, so the tests are built around not considering the data source. Mocking Amplify properly to simulate data coming in and out of Amplify is significantly more work, and to put it mildly, I'm not familiar enough with Amplify to pull it off. 

I'm pretty sure it isn't possible, as [the CLI mock page](https://docs.amplify.aws/cli/usage/mock/) doesn't list neither MQTT nor auth, which means the first-class option is likely off the table. This includes any auth-related components, 

As far as I'm aware, the simplest option (shy of making a secondary server to pose as AWS with the functionality we use, which is an entire project onto itself and not something we can pull off inside an existing project in the time we have left) is disabling Amplify entirely, and passing null instances to consumers to signal a mocking state


As for the specific changes:

>   we wont use env variables exactly in the same way.

Why not for this particular variable? It's an easy way to flag to disable real connections

>    AmplifyInstance will be contrsucted but data are not reciveable until user is signed in.

The environment variable sets a flag that simply doesn't initialise the Amplify instance, which propagates down to all consumer components. I don't see any reason why that still can't be done

**Comment by javidaf** [comment]
Ok I understand and I see the point here now, . My understand came from MochingComponent that actually is used for tests the charts and not amplify in any sence. 

Will clarify that the feature changes:

1. Will introduce new and remove some of current env varibles.

I will approve for merge!

**Review by javidaf — APPROVED** [review]

**Pull request merged**
